02-RTB/documenti-esterni/verbali/2024-11-19.typ
lib/common.typ

Redazione verbale esterno, aggiunta in common.typ le chiavi per i membri di M31.

Redazione per #40

---

.github/workflows/compile.py

@lorislibralato puoi già fare merge secondo me

fix: correctly sort documents based on date

---

02-RTB/diari/2025-01-08.typ

Artefatti: https://sbkd.us.to/altd/6d5a8fd63cde7c26713439832a4e1504505b1ebc

Realizzato Diario di Bordo del 08 Gennaio 2025 #85

---

02-RTB/documenti-interni/verbali/2025-01-07.typ
lib/common.typ

Artefatti: https://sbkd.us.to/altd/5ede624f272ec3f0239fa91e8a408695fcd6d017

92 redazione verbale interno 07 01 2025

---

02-RTB/documenti-interni/verbali/2025-01-22.typ

Artefatti: https://sbkd.us.to/altd/0c65f0db045bb3826c2c127b9d3135cfeabaf1db

verbale interno 2025-01-22

---

02-RTB/documenti-esterni/verbali/2024-12-03.typ
02-RTB/documenti-esterni/verbali/2024-12-17.typ
02-RTB/documenti-esterni/verbali/2025-01-28.typ
02-RTB/documenti-interni/verbali/2024-12-04.typ
lib/verbale.typ

Artefatti: https://sbkd.us.to/altd/80a0bbd28469cd0bac28fc67bfa3cf06ddb23d98

Redazione verbale esterno #111

---

.github/workflows/push.yml
02-RTB/presentazione-tecnologie.typ
website/index.html

Come da titolo, questa PR aggiunge le slide di presentazione del PoCCome da titolo, questa PR aggiunge le slide di presentazione del PoCCome da titolo, questa PR aggiunge le slide di presentazione del PoCCome da titolo, questa PR aggiunge le slide di presentazione del PoC
Artefatti: https://sbkd.us.to/altd/1fbfc01c79d6b13af10384def287c54c2ad6f447

Slides di presentazione del PoC

---

02-RTB/documenti-esterni/analisi-requisiti.typ
02-RTB/documenti-esterni/piano-di-qualifica.typ
02-RTB/documenti-interni/norme-progetto.typ

Artefatti: https://sbkd.us.to/altd/34b519316faace3d626747f8792478f2c124c54a

ultimi fix 2

---

.github/workflows/compile.py
02-RTB/documenti-esterni/piano-di-progetto.typ
02-RTB/documenti-esterni/piano-di-qualifica.typ
02-RTB/documenti-interni/norme-progetto.typ
02-RTB/documenti-interni/verbali/2025-01-22.typ
02-RTB/lettera-rtb.typ
lib/importantdocs.typ
website/glossario.html
website/index.html

Artefatti: https://sbkd.us.to/altd/cb5bce407606cdb6a898f9c9d6993797f0f8ae20

Lettera di candidatura alla RTB

---

02-RTB/documenti-esterni/piano-di-progetto.typ
02-RTB/documenti-esterni/piano-di-qualifica.typ
02-RTB/documenti-interni/norme-progetto.typ

Artefatti: https://sbkd.us.to/altd/9a60b3ba6aef3e1b72d5699c0108d58dd01cf7a8

Boh, something

---

.github/workflows/push.yml
03-PB/documenti-esterni/manuale-utente.typ
03-PB/manuale-utente/01-getting-started/index.md
03-PB/manuale-utente/02-guides/index.md
03-PB/manuale-utente/02-guides/registrazione.md
03-PB/manuale-utente/assets/altd.png
03-PB/manuale-utente/index.md
lib/importantdocs.typ
mkdocs.yml
pyproject.toml
uv.lock
website/index.html

Artefatti: https://sbkd.us.to/altd/2fd70fb5eed0bb75c2ed06f0ed050ae13e409728

Inizio del manuale utente

---

.github/workflows/compile.py

Artefatti: https://sbkd.us.to/altd/6adb89b56bbcdcd3866296487c20fd55d8bab3e6

Risolta visualizzazione errata nome Manuale Utente e Specifica Tecnica

---

03-PB/documenti-esterni/verbali/2025-02-28.typ

Artefatti: https://sbkd.us.to/altd/d1a739561644b8f432e92c7b864d68c5045c24cb

157 redazione verbale esterno 28 02

---

03-PB/documenti-interni/verbali/2025-03-03.typ

Artefatti: https://sbkd.us.to/altd/934164ae83f961a3d68b653761a39731966a60ca

169 redazione verbale interno 03 03 2025

---

03-PB/documenti-interni/norme-progetto.typ

Artefatti: https://sbkd.us.to/altd/6fa2a9d6424bfc82953846dd876f1477bbc76f02

Sistemazione NdP 

---

.github/workflows/glossary.py
03-PB/documenti-esterni/specifica-tecnica.typ
03-PB/documenti-interni/glossario.typ
03-PB/documenti-interni/glossario.yml
03-PB/documenti-interni/norme-progetto.typ
03-PB/documenti-interni/verbali/2025-03-03.typ
03-PB/documenti-interni/verbali/2025-03-11.typ
03-PB/manuale-utente/concetti/merci.md
03-PB/manuale-utente/concetti/ordini.md
03-PB/manuale-utente/concetti/riassortimenti.md
03-PB/manuale-utente/concetti/tipi-utenti.md
03-PB/manuale-utente/concetti/trasferimenti.md

Artefatti: https://sbkd.us.to/altd/7da6c355e6d03363a12bfc19322cad97def20156

Ampliamento glossario

---

03-PB/diari/2025-03-25.typ

Artefatti: https://sbkd.us.to/altd/2b0b108b406f7d9537b58d507912a5afa5dd86eb

ddb 25-03-2025

---

03-PB/documenti-esterni/specifica-tecnica.typ

Artefatti: https://sbkd.us.to/altd/0381b1a9cc800db9c7a13e1e6b3f8ac44e43d55f

Informazioni funzionamento order microservice

---

03-PB/documenti-interni/verbali/2025-03-25.typ
03-PB/documenti-interni/verbali/2025-03-31.typ

Artefatti: https://sbkd.us.to/altd/51294a12c7d941fa0dab12f8bf7c2a98238e0571

228 redazione verbale 31 03

---

.github/workflows/glossary.py
.github/workflows/push.yml
03-PB/manuale-utente/concetti/merci.md
03-PB/manuale-utente/concetti/ordini.md
03-PB/manuale-utente/concetti/riassortimenti.md
03-PB/manuale-utente/concetti/tipi-utenti.md
03-PB/manuale-utente/concetti/trasferimenti.md
03-PB/manuale-utente/guide/aggiunta-stock.md
03-PB/manuale-utente/guide/ordine.md
03-PB/manuale-utente/guide/rimozione-stock.md
03-PB/manuale-utente/guide/trasferimento.md
03-PB/manuale-utente/installazione/preparazione-del-sistema/01-installazione-sw.md
03-PB/manuale-utente/operazione/Test.md
03-PB/manuale-utente/telemetria/config.md
03-PB/manuale-utente/telemetria/dashboard.md

Artefatti: https://sbkd.us.to/altd/3665ebf0bd916777b58742a400034d1cd66d640b

Quick Fix MU

---

03-PB/documenti-esterni/piano-di-progetto.typ

Artefatti: https://sbkd.us.to/altd/828543e352277ad8c80849b53fdd1bbfc2dfd717

215 piano di progetto aggiornare la pianificazione a lungo termine
